/* eslint-disable prettier/prettier */
import { Module } from '@nestjs/common';
import { SettingsService } from './settings.service';
import { SettingsController } from './settings.controller';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContactDetails, CurrencyOptions, DeliveryTime, EmailAdmin, EmailCustomer, EmailVendor, Location,LogoSettings,PaymentGateway,SeoSettings, ServerInfo, Setting, SettingsOptions, ShopSocials } from './entities/setting.entity';
import { ContactDetailsRepository, CurrencyOptionsRepository, DeliveryTimeRepository, EmailAdminRepository, EmailCustomerRepository, EmailVendorRepository, LocationRepository, LogoSettingsRepository, OptionPaymentRepository, SeoSettingsRepository, ServerInfoRepository, SettingOptionsRepository, SettingRepository, ShopSocialsRepository } from './settings.repository';

@Module({
  imports: [TypeOrmModule.forFeature([Setting, 
            SettingOptionsRepository, 
            SettingsOptions,SeoSettings,
            SeoSettingsRepository,
            ServerInfo,
            ServerInfoRepository,
            DeliveryTime,
            DeliveryTimeRepository,
            ContactDetailsRepository,
            ShopSocialsRepository,
            LocationRepository,
            Location,
            ShopSocials,
            ContactDetails,
            PaymentGateway,
            OptionPaymentRepository,
            CurrencyOptionsRepository,
            CurrencyOptions,
            EmailAdminRepository,
            EmailAdmin,
            EmailVendorRepository,
            EmailVendor,
            EmailCustomerRepository,
            EmailCustomer,
            LogoSettingsRepository,
            LogoSettings
        ])],
  controllers: [SettingsController],
  providers: [SettingsService, 
              SettingRepository, 
              SeoSettingsRepository,
              SettingOptionsRepository, 
              SettingsOptions,ServerInfo,ServerInfoRepository, DeliveryTime,
              DeliveryTimeRepository,
              ContactDetailsRepository,
              ShopSocialsRepository,
              LocationRepository,
              Location,
              ShopSocials,
              ContactDetails,
              PaymentGateway,
              OptionPaymentRepository,
              CurrencyOptionsRepository,
              CurrencyOptions,
              EmailAdminRepository,
              EmailAdmin,
              EmailVendorRepository,
              EmailVendor,
              EmailCustomerRepository,
              EmailCustomer,
              LogoSettingsRepository,
              LogoSettings],
  exports: [SettingsService,
            SettingRepository, 
            SeoSettingsRepository, 
            SettingOptionsRepository, 
            SettingsOptions,ServerInfo,ServerInfoRepository, DeliveryTime,
            DeliveryTimeRepository,
            ContactDetailsRepository,
            ShopSocialsRepository,
            LocationRepository,
            Location,
            ShopSocials,
            ContactDetails,
            PaymentGateway,
            OptionPaymentRepository,
            CurrencyOptionsRepository,
            CurrencyOptions,
            EmailAdminRepository,
            EmailAdmin,
            EmailVendorRepository,
            EmailVendor,
            EmailCustomerRepository,
            EmailCustomer,
            LogoSettingsRepository,
            LogoSettings],
})
export class SettingsModule {}
